openapi: 3.1.0
info:
  version: 1.0.0
  title: Students app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of students app
tags:
  - name: Students
    description: Operations about users.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  - url: https://chat-backend-r0za.onrender.com1
security: []
paths:
  /chats:
    get:
      $ref: ../swagger/paths/chats/get.yaml
    post:
      $ref: ../swagger/paths/chats/post.yaml
  /chats/{id}:
    get:
      $ref: ../swagger/paths/chats/{id}/get.yaml
    delete:
      $ref: ../swagger/paths/chats/{id}/delete.yaml
    patch:
      $ref: ../swagger/paths/chats/{id}/patch.yaml
